### ISSUE TITLE
Better notification management

### ISSUE THREAD

**Issue by benboeser** [reviewninja/review.ninja#662] opened 2015-01-17 00:26 UTC
Many interviewees complained about notifications and are unclear what’s coming from GitHub vs. ReviewNinja. A few suggested that they would only like to be notified of a pending review if the build has passed, so they don’t waste time.

**Comment by dfarr** [comment] 2015-01-19 17:30
I think this problem could be solved by adding some more personality to our emails. @fabianschwarzfritz has addressed this, I think we should reconsider everything about emails from why we send them to the wording.

**Comment by dfarr** [comment] 2015-01-19 17:32
As for the "only notify on build pass", this is not possible as GitHub is not the source of truth of this information and we cannot know what CI system the team has accepted as *their* source of truth.

**Comment by fabianschwarzfritz** [comment] 2015-01-22 19:47
As we cannot change the github notifications, we could make our notifications more "review-ninja" like. 

This includes a better text of course, but also the design of the email. Related to #670.

**Comment by rwreynard** [comment] 2015-01-26 19:07
Notification emails sent for:

- All issues closed
- New issue
- Pull request opened
- New commits on pull request
- Pull request starred / unstarred

**Comment by withkiki** [comment] 2015-02-02 23:27
@fabianschwarzfritz 

![rn-email-alert](https://cloud.githubusercontent.com/assets/7938229/6011378/038143b6-aaf0-11e4-8aa3-446e0282574a.png)
![rn-email-alert-update-specs](https://cloud.githubusercontent.com/assets/7938229/6011377/03699982-aaf0-11e4-8fbb-7d5c179a41b6.png)

Icon used:
issue:https://octicons.github.com/icon/issue-opened/
email:http://fortawesome.github.io/Font-Awesome/icon/envelope/
twitter:
favicon:

**Comment by fabianschwarzfritz** [comment] 2015-02-03 00:14
:+1:

**Comment by rwreynard** [comment] 2015-02-04 14:14
@withkiki does it make more sense for the call to action (the button label) to be: "View in ReviewNinja" ?

Also tighten up the alignment, are you using a grid? The header and footer look fine, but the main content is floating around, don't center it.

I think your type sizes look miniscule - double check! 

Also margins, for instance the top margin "35px" - the content seems to be about 100px below the header, so what do you mean by 35px?

Where do the links go, e.g., "dfarr" underlined? If they go to GitHub (I'm guessing) do we want that? Does it make more sense to help people focus and do the one primary action from the email (e.g., view the issue in ReviewNinja)?

**Comment by rwreynard** [comment] 2015-02-04 14:38
@withkiki - for the footer: this isn't a marketing email, do we want all these links to other places? Maybe we should keep it simple?

Also, for the last note I suggest: You received this email because you asked to be notified about issues opened or closed in ReviewNinja. You can manage notifications in ReviewNinja. ("manage notifications in ReviewNinja" is the link). It's a good idea to try to avoid "click here" wherever possible, some info here: http://www.smashingmagazine.com/2012/06/20/links-should-never-say-click-here/

Can this email be replied to? We should manage expectations either way.

**Comment by withkiki** [comment] 2015-02-04 19:17
@rwreynard , hey, Rachel, will you be able to talk tomorrow(thursday) morning at USA 8:AM, you local time 5:pm, i also have "staged access design" want to discuss with you. 

For the questions you've listed, 

1. The "see pull request" button is always linking to the "pull request list page", the previous version was "see more".. @dfarr @fabianschwarzfritz @benboeser, Rachel suggested to change the button to "View in ReviewNinja", since the button call action to go to the ReviewNinja tool. It makes sense to me, how do you think? 
BTW, a good article for email design.
http://webdesign.tutsplus.com/articles/the-complete-guide-to-designing-for-email--webdesign-12941

2.Yes, i used grid. After discussion with @fabianschwarzfritz, form his implementation perspective, he wish the middle part was treat as a overall unit, include issue button (orange). Let' me talk to @fabianschwarzfritz again, to see if it is ok to separate orange issue icon from the green content, and get the green part centered.

3.Font type sizes look minuscule, yes, i remember we are usually using 10-14pt in web. I will double check, Sorry for this.

4.35px Margin was based on the out borderline, not measured from the header to the green content. Since the content length are not fixed, so i marked a border for implementation.

5. The destination of the username e.g."dfarr links", i assume it's linked to the reviewninja? @dfarr 
But the other links, e.g.PR, Repo are definitely go to the ReviewNInja tool. 

6. The footer design, i agree with to keep it as quiet & simple. That is why the main message was designed big and loud, to guide the focusing. But i also think we should keep somehow a communication path for users. @benboeser @dfarr @fabianschwarzfritz. ideas?

7. Thanks for the article, i will change the format of "click here".

**Comment by benboeser** [comment] 2015-02-04 20:01
@withkiki - i think it is okay to remove the twitter handles, etc from the bar. It is pretty unusual in notification emails to have those. And that makes it cleaner...

The 'View in ReviewNinja' also sounds good...

**Comment by withkiki** [comment] 2015-02-04 22:24
Okay, then i will let Fabian know.

**Comment by fabianschwarzfritz** [comment] 2015-02-04 22:35
:+1:

**Comment by withkiki** [comment] 2015-02-06 22:53
Updated version @fabianschwarzfritz  @rwreynard 
![screen shot 2015-02-06 at 2 50 31 pm](https://cloud.githubusercontent.com/assets/7938229/6088861/d177ae5a-ae0f-11e4-9d5e-76a91f2b689a.png)
![screen shot 2015-02-06 at 2 52 03 pm](https://cloud.githubusercontent.com/assets/7938229/6088862/d177bef4-ae0f-11e4-9bc0-4741676d59dd.png)

**Comment by rwreynard** [comment] 2015-02-07 15:50
Recommend left aligning the button with the text & reducing the space between the issue icon and the text, otherwise :+1:

**Comment by rwreynard** [comment] 2015-02-07 16:09
Also make the issue icon a little smaller, we want the button to be the most prominent element (with bold text?) and it's competing with the giant icon a bit at the moment :)

**Comment by withkiki** [comment] 2015-02-09 19:42
:bouquet: @fabianschwarzfritz

**Comment by fabianschwarzfritz** [comment] 2015-02-10 16:54
![screen shot 2015-02-10 at 8 54 21 am](https://cloud.githubusercontent.com/assets/1759672/6131676/7a17dab8-b102-11e4-867d-6ea550a8c218.png)

**Comment by withkiki** [comment] 2015-02-10 17:22
Hey! @fabianschwarzfritz, first thanks, and the second,
would you align the issue icon with the Review Ninja logo? And a little closer to the message text part might be better. I knew you've said we couldn't use Open Sans, nevertheless Helvetica was easier & possible to implement. Since the different property of two typefaces, there is a little unbalancing of the current footer section, (fonts piled together, and somehow distracting). I suggest to decrease the fonts size, We can tune it together.

**Comment by fabianschwarzfritz** [comment] 2015-02-10 17:45
Hi @withkiki. As I told you we had to change to use tables instead of div yesterday, and I forgot to adjust the margin. I fixed that, it's an easy one.

Since we were spending a lot of time in the details of those emails and changed especially the font sizes back and forth several times, I'd like to push this functionality out first. I'll implement the texts and the icons. By doing this the user is not distracted by the two different emails from github.com and reviewninja app anymore and we can make sure this issue is solved. 

When this is done I'll sit together with you and do the rest of the design improvements.

**Comment by withkiki** [comment] 2015-02-16 23:19
![issue-closed-transparent-43px-43px](https://cloud.githubusercontent.com/assets/7938229/6220758/2af52c64-b5ef-11e4-8be4-f0eae1980a51.png)
![issue-open-transparent-43px-43px](https://cloud.githubusercontent.com/assets/7938229/6220759/2afcf03e-b5ef-11e4-95ce-4a669bb2cfd5.png)
![ninja-pullrequest-transparent-43px-43px](https://cloud.githubusercontent.com/assets/7938229/6220762/2affad42-b5ef-11e4-9489-6235e963bdac.png)
![ninja-star-unstared-43px-43px](https://cloud.githubusercontent.com/assets/7938229/6220760/2afe406a-b5ef-11e4-83dc-af7ebf1b2229.png)
![ninja-stared-43px-43px](https://cloud.githubusercontent.com/assets/7938229/6220761/2afef17c-b5ef-11e4-94db-ab6c740ba1db.png)

**Comment by fabianschwarzfritz** [comment] 2015-02-16 23:31
Thanks @withkiki, done with #751

**Closed by fabianschwarzfritz** 2015-02-16 23:31 UTC
Labels: enhancement, idea, prio high
