### ISSUE TITLE
Add settings option to require code review by person other than the pull request author

### ISSUE THREAD

**Issue by stephanzlatarev** [reviewninja/review.ninja#1010] opened 2015-12-01 09:26 UTC
Feature request: Add settings option that can be used to require at least one ninja star from a person other than the author of the pull request.
If this is already possible, please, document it. The best workaround I know is to set the number of required ninja stars to at least 2, so that the ninja star of the author is not sufficient for a merge.

**Comment by dfarr** [comment] 2015-12-01 18:52
Duplicate of #1008. Please feel free to join the discussion there :)

**Comment by stephanzlatarev** [comment] 2015-12-02 08:25
I read through #1008 before opening this issue. This request is for a separate feature. I would like to be able to enforce four eyes principle code review within the same team. #1008 will give me approval by a team that is authorized to merge pull requests but will not prevent anyone from that team to merge a pull request without consulting with a second person. For example, one person from the authorized team can create a new pull request, give a ninja star and then merge the pull request.

**Comment by stephanzlatarev** [comment] 2015-12-02 08:36
Just for illustration of the use case, what I am looking for is something like this:

(preferred by me) "[checkbox] For reviewninja/foo four eyes principle is required to merge. I.e. ninja stars by author do not count."
(less preferred by me) "[checkbox] For reviewninja/foo authors cannot give ninja stars"

**Comment by dfarr** [comment] 2015-12-02 18:25
Would increasing the ninja star threshold to 2 solve this? 

A PR is authored by one person, but can have multiple committers. It is possible that the the PR is opened by someone who didn't even write any of the code, in such a case it would be valid for this person to give a ninja star.

**Comment by stephanzlatarev** [comment] 2015-12-04 18:44
Sorry, maybe you read the description of the issue as if it is impossible for me to enforce the four eyes principle code review at all, while I mean that what ReviewNinja offers is cumbersome in our setup. Yes, like I wrote in the description of the issue the best workaround I got to is setting the ninja star threshold to 2. It still feels like a workaround, though.
Our dev process says once a developer gets a change ready to be pulled, they should create the pull request and should get the change reviewed by somebody else from the team before it can be merged. In essence, I should not be able to click on the "Merge" button unless I get a ninja star from somebody else. Now when I get a ninja star from somebody else, why should I need to give my own pull request a second ninja star in order to be able to merge it? It feels more natural that I should be able to merge it right away. Of course, if I, at any point of time, decide that I do not want the pull request to be merged, I can close the pull request.
This feature request aims at increased convenience, i.e. less clicks to do the same thing.

@dfarr you say that it is a valid case for someone who opens a PR to give a ninja star. I agree. Do you think it is a valid case for that person to NOT give a ninja star? What would be the use case for that? Why would you create a pull request if you did not want the change to get merged?

**Comment by dfarr** [comment] 2015-12-04 20:16
It is common to open a PR before it is even ready to be merged - it is work in progress. When this happens commits will be added to the PR until the PR is completed. 

In this scenario a ninja star by the author (or primary contributor) of the PR could indicate that the code is now ready to be reviewed. Conversely, if this person does not give a ninja star, it would mean that the PR is not ready to be reviewed and therefore not worth a colleagues time (yet).

**Comment by jbjonesjr** [comment] 2015-12-04 21:05
interesting workflow @dfarr to use the initial star as a signal that the PR is ready to be reviewed, but not sure if that is a beneficial workaround. Few points:
* Since you are still short stars, no new status available on the pull request page (it's still yellow/unmergable)
* Since webhooks or notifications don't fire on status change, there is no way to notify the rest of the review team without a comment.
  * And if you are writing a comment anyway, i would just use the :ship: emojii and `@mention` instead.

I think at the end of the day, you propose an interesting and novel workaround, but it just that. I think that it is a good solution for the short term, but think the primary requirement is strong enough that it could still be a backlogged feature.

**Note:** The definition of "author" for a PR needs to be strictly defined. I would argue that it is the person who creates a PR.

**Comment by dfarr** [comment] 2015-12-07 21:48
Okay, let reopen this issue :smile:

**Comment by dfarr** [comment] 2015-12-07 21:56
Proposal: PR #1008 will support "require n ninja stars from team m". Where m defaults to "anybody".

*If* your repository has been configured to require ninja stars from a team, we could have some additional functionality.

- `@mention` the review team to send out a special RN email to let the team know a review is ready
- disallow ninja stars from the *author* of the PR
- disallow ninja stars from any *contributor* of the PR

Please feel free to add more idea!

I propose only showing such options when you have configured your repo to require ninja stars from a team in order to keep the buy in for RN low. By default it's still simply a single star from anybody.

**Comment by thojansen** [comment] 2015-12-07 22:04
:+1: this should add enough flexibility

**Comment by stephanzlatarev** [comment] 2015-12-15 18:39
Excellent! These configuration options will nicely fit our needs

**Comment by mathiaswagner** [comment] 2015-12-17 09:50
:+1:

**Comment by dfarr** [comment] 2016-01-06 19:30
For the time being this is not something we will pursue, but will keep the proposal mentioned above in case we decide to pursue it in the future.

We suggest increasing the number required ninja stars to >1 and assigning a review team (see #1008)

**Closed by dfarr** 2016-01-06 19:30 UTC
Labels: feature request
