### ISSUE TITLE
Team missing when configuring threshold

### ISSUE THREAD

**Issue by pgmillon** [reviewninja/review.ninja#1059] opened 2016-04-13 08:48 UTC
Hi,
I'd like to restrict ninja stars for the repository https://github.com/nuxeo/nuxeo to the https://github.com/orgs/nuxeo/teams/reviewers/ team (one out of 42) but the team is not displayed in the drop-down teams list (there are only 31 items in the list).

**Comment by jcarsique** [comment] 2016-04-26 12:38
@reviewninja, would you have an idea about the root cause? This issue is really blocker: we cannot assign the right people (nor the nuxeo/reviewers team, nor any new team), only reuse old teams which content does not match.

**Comment by jcarsique** [comment] 2016-04-26 13:01
Actually, this seems to be a simple paging issue: renaming "Reviewers" to "core-reviewers", I could see and assign it. 
Rename on GitHub side works fine but if I give the name a name alphabetically greater than the last displayed team ("marketing" in our case), then there's an issue and the team is no more editable on reviewninja side.

So, for now, the workaround is enough: we'll name the team so that it appears in the first page of the teams list. 
However this is not sustainable at long term: that could be break at any time if we add too much teams before (in the alphabetical order) or if GitHub changes its API page size or teams order.

**Comment by casche** [comment] 2016-04-26 15:57
Hey @jcarsique and @pgmillon, thanks for pointing this out. 

We'll look into this soon and add pagination to the teams list to ensure all teams will be visible. 👍

**Closed** 2016-05-02 21:56 UTC
Labels: bug, high, IMPLEMENT
