### ISSUE TITLE
Expose github path prefix as env variable

### ISSUE THREAD

**Issue by dfarr** [reviewninja/review.ninja#572] opened 2014-11-26 19:36 UTC
https://github.com/reviewninja/review.ninja/blob/master/src/server/services/github.js#L15

See issue #409

**Comment by fabianschwarzfritz** [comment] 2015-01-08 19:48
@dfarr Can you please explain this a little further? I'd be very happy about that because I don't get what the issue is about so far. 

What I got so far: Currently it's already possible to configure the host via server.github.enterprise and the according env variable GITHUB_API_HOST. So what is missing here?

**Comment by fabianschwarzfritz** [comment] 2015-01-12 19:20
Fixed with  #637

**Closed by fabianschwarzfritz** 2015-01-12 19:20 UTC
Labels: bug

**Comment by dfarr** [comment] 2015-01-14 01:56
:+1:
