### ISSUE TITLE
"Merge" button does not update

### ISSUE THREAD

**Issue by MitchK** [reviewninja/review.ninja#1126] opened 2016-11-28 21:47 UTC
On our internal review ninja when we click the "merge button" it will not show "merged". It will show a short loading animation and do nothing. When I refresh the page, I see the "merged" indication.

I checked the browser logs and can't see any error messages. The "call" request is successful.

**Comment by dfarr** [comment] 2017-01-04 20:29
This is most likely caused by a delay in the webhook "merged" message from GH. Will leave as-is.

**Closed by dfarr** 2017-01-04 20:29 UTC
Labels: bug
